export { AgentChatClient } from "./client";
export { AgentChatREST, type RESTClientOptions } from "./rest";
export type {
  // Data types
  AgentCard,
  AgentPresence,
  AgentStatus,
  AgentStatusUpdate,
  ChannelRole,
  ChannelType,
  ChatMessage,
  ClientOptions,
  ConsensusRule,
  ContentType,
  MessageDeleted,
  MessageEdited,
  PinAction,
  PinUpdate,
  ReactionAction,
  ReactionUpdate,
  ReadReceiptUpdate,
  RoleUpdate,
  SenderType,
  ThreadReply,
  ThreadUpdate,
  VoteDecision,
  VoteResult,
  // Handler types
  DeleteHandler,
  EditHandler,
  ErrorHandler,
  MessageHandler,
  PresenceHandler,
  ReactionHandler,
  ThreadHandler,
  VoteResultHandler,
  // Full protocol message types (48 total)
  ACMessage,
  AuthMessage,
  AuthOKMessage,
  JoinChannelMessage,
  LeaveChannelMessage,
  CreateChannelMessage,
  ChannelCreatedMessage,
  ProposalMessage,
  VoteMessage,
  VoteResultMessage,
  TakeoverMessage,
  HandbackMessage,
  DiscoverMessage,
  DiscoverResultMessage,
  ErrorMessage,
  PingMessage,
  PongMessage,
  ForwardMessage,
  MessageAck,
  ReactionMessage,
  PinMessage,
  ThreadMessage,
  EditMessageCmd,
  DeleteMessageCmd,
  ReadReceiptMessage,
  SetRoleMessage,
  SetStatusMessage,
  TypingMessage,
  ArchiveChannelMessage,
  ChannelArchivedMessage,
  SetTopicMessage,
  TopicUpdateMessage,
  // V2: Raft + DAG
  TaskStatus,
  TaskNode,
  RequestVoteMessage,
  VoteGrantedMessage,
  LeaderElectedMessage,
  CreateDAGMessage,
  AssignTaskMessage,
  TaskUpdateMessage,
  TaskVerifiedMessage,
  AgentStatusBroadcast,
} from "./types";
